#!/usr/bin/env python3
"""
Script to generate LLM prompts for individual puzzles in JavaScript or Python format.

This script extracts puzzle information from the generator files and formats
prompts similar to the llm_instructions.md generated by generate_instructions.js.
"""

import os
import re
from pathlib import Path
import json
import sys
import importlib

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

print("Current dir:", os.getcwd())
print("Script dir:", os.path.dirname(__file__))
print("Project root:", os.path.dirname(os.path.dirname(__file__)))
print("Python path:", sys.path)

# Directory paths
project_root = Path(os.path.dirname(os.path.dirname(__file__)))
js_generators_dir = project_root / "build_src" / "js_puzzles" / "generators"
python_generators_dir = project_root / "infinite_rl" / "python_puzzles" / "generators"


def _extract_balanced_value(text):
    """
    Extract a balanced JavaScript value (object or array) from text.

    Handles nested braces and brackets properly.
    Returns the extracted value string, or None if invalid.
    """
    text = text.lstrip()
    if not text:
        return None

    # Determine if it's an object {...} or array [...]
    if text[0] == "{":
        open_char, close_char = "{", "}"
    elif text[0] == "[":
        open_char, close_char = "[", "]"
    else:
        # Try to match a simple value (number, string, etc.)
        # Match until semicolon or closing brace
        simple_match = re.match(r"[^;}\n]+", text)
        if simple_match:
            return simple_match.group(0).rstrip()
        return None

    # Balance braces/brackets
    depth = 0
    in_string = False
    string_char = None
    i = 0

    for i, char in enumerate(text):
        # Handle string literals
        if char in ('"', "'") and (i == 0 or text[i - 1] != "\\"):
            if in_string and string_char == char:
                in_string = False
                string_char = None
            elif not in_string:
                in_string = True
                string_char = char
            continue

        if in_string:
            continue

        # Track nesting depth
        if char in ("{", "["):
            if char == open_char:
                depth += 1
        elif char in ("}", "]"):
            if char == close_char:
                depth -= 1
                if depth == 0:
                    # Found the closing bracket/brace
                    return text[: i + 1].strip()

    # If we didn't find a balanced expression, return None
    return None


def _extract_balanced_function(text, func_name):
    """
    Extract a balanced JavaScript function from text.

    Finds 'static func_name' and extracts until the matching closing brace.
    """
    text = text.lstrip()
    # Find the start
    start_pattern = rf"static {re.escape(func_name)} \("
    start_match = re.search(start_pattern, text)
    if not start_match:
        return None

    start_idx = start_match.start()
    # Now find the opening brace after the params
    params_end = text.find("{", start_idx)
    if params_end == -1:
        return None

    # Now balance from params_end
    depth = 0
    in_string = False
    string_char = None
    i = params_end

    while i < len(text):
        char = text[i]
        # Handle string literals
        if char in ('"', "'") and (i == 0 or text[i - 1] != "\\"):
            if in_string and string_char == char:
                in_string = False
                string_char = None
            elif not in_string:
                in_string = True
                string_char = char
        elif in_string:
            pass
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start_idx : i + 1].strip()
        i += 1

    return None


def extract_js_puzzle_info(file_path, puzzle_name):
    """Extract puzzle information from a JavaScript generator file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except:
        return None

    # Find the class
    class_match = re.search(
        rf"export class {re.escape(puzzle_name)} extends PuzzleGenerator", content
    )
    if not class_match:
        return None

    # Check if the class is commented out (// before export)
    line_start = content.rfind("\n", 0, class_match.start()) + 1
    line_before_class = content[line_start : class_match.start()]
    if line_before_class.strip().startswith("//"):
        # This class is commented out, skip it
        return None

    class_start = class_match.end()

    # Find next class or end
    next_class_match = re.search(
        r"export class \w+ extends PuzzleGenerator", content[class_start:]
    )
    class_end = class_start + (
        next_class_match.start() if next_class_match else len(content[class_start:])
    )

    class_content = content[class_start:class_end]

    # Extract docstring
    docstring_match = re.search(
        r'static docstring = ["\']([^"\']*)["\']', class_content
    )
    docstring = docstring_match.group(1) if docstring_match else ""
    docstring = docstring.replace(r"\n", "\n").replace(r"\t", "\t")

    # Extract sat function
    sat = _extract_balanced_function(class_content, "sat")
    sat = sat.replace("static sat", "function sat") if sat else ""
    # Normalize tabs to 4 spaces
    sat = sat.replace("\t", "    ")
    # Remove one level of indentation (from being inside a class)
    sat_lines = sat.split("\n")
    sat = "\n".join(line[4:] if line.startswith("    ") else line for line in sat_lines)

    # Extract sol function header
    sol_match = re.search(r"static sol \([^)]*\)", class_content)
    sol = sol_match.group(0).replace("static sol", "function sol") if sol_match else ""

    # Extract getExample and update sol parameters
    example_inputs = {}
    # Find getExample() method and extract the returned value
    # More flexible regex to handle different formatting
    getex_match = re.search(r"getExample\s*\(\s*\)\s*\{", class_content)
    if getex_match:
        # Find the return statement within the method
        start_pos = getex_match.end()
        return_match = re.search(r"return\s+", class_content[start_pos:])
        if return_match:
            # Start from after 'return '
            return_start = start_pos + return_match.end()

            # Extract the value by balancing braces/brackets
            value_str = _extract_balanced_value(class_content[return_start:])

            if value_str:
                try:
                    # Convert JavaScript object syntax to valid JSON
                    js_obj_str = value_str
                    # Remove trailing commas before ] or }
                    js_obj_str = re.sub(r",(\s*[}\]])", r"\1", js_obj_str)
                    # Fix float literals with trailing dots: 0. -> 0.0, -1. -> -1.0
                    js_obj_str = re.sub(r"(\d)\.(\s*[,\]\}])", r"\1.0\2", js_obj_str)
                    # Add quotes around unquoted object keys: { key: value } -> { "key": value }
                    # Match identifiers OR numbers, but only when preceded by { or ,
                    js_obj_str = re.sub(
                        r"([{,]\s*)([a-zA-Z_]\w*|[0-9]+)(:)", r'\1"\2"\3', js_obj_str
                    )
                    # Replace single-quoted strings with double-quoted strings
                    # Only match single quotes that delimit strings (not inside double-quoted strings)
                    js_obj_str = re.sub(r"'([^']*)'", r'"\1"', js_obj_str)

                    # Parse as JSON
                    import json

                    example_obj = json.loads(js_obj_str)

                    if isinstance(example_obj, dict):
                        example_inputs = example_obj
                        if sol:
                            params = ", ".join(
                                f"{k} = {repr(v)}" for k, v in example_obj.items()
                            )
                            if params:
                                sol = f"function sol({params})"
                    elif isinstance(example_obj, list):
                        # For lists, find the first parameter name from sat function
                        sat_params_match = re.search(
                            r"static sat \(([^)]*)\)", class_content
                        )
                        if sat_params_match:
                            param_names = [
                                p.strip().split("=")[0].strip()
                                for p in sat_params_match[1].split(",")
                                if p.strip()
                            ]
                            if (
                                param_names and len(param_names) > 1
                            ):  # Skip 'answer' param
                                example_inputs = {param_names[1]: example_obj}
                                if sol:
                                    params = f"{param_names[1]} = {repr(example_obj)}"
                                    if params:
                                        sol = f"function sol({params})"
                except Exception as e:
                    # Log the error for debugging
                    import traceback

                    print(
                        f"  WARNING: Failed to parse example in {puzzle_name}: {e}",
                        file=sys.stderr,
                    )
                    print(f"    Raw value: {value_str}", file=sys.stderr)
                    print(f"    After conversions: {js_obj_str}", file=sys.stderr)

    return {
        "docstring": docstring,
        "sat": sat,
        "sol": sol,
        "ans_type": None,
        "example": example_inputs,
    }


def extract_python_puzzle_info(file_path, puzzle_name):
    """Extract puzzle information from a Python generator file."""
    try:
        # Import the module and get the class
        module_name = file_path.stem
        module = importlib.import_module(
            f"infinite_rl.python_puzzles.generators.{module_name}"
        )
        cls = getattr(module, puzzle_name)
        gen = cls()

        docstring = gen.docstring
        if docstring:
            docstring = docstring.strip(' "').strip("\n")
            # Unindent if multiple lines
            lines = docstring.split("\n")
            if len(lines) > 1:
                first_line_indent = len(lines[1]) - len(lines[1].lstrip())
                docstring = "\n".join(
                    (
                        line[first_line_indent:]
                        if line.startswith(" " * first_line_indent)
                        else line
                    )
                    for line in lines
                )

        sat_code = gen.sat_src
        ans_type = gen.ans_type
        example = gen.get_example()

        # Generate sol header from arg_names
        if gen.arg_names:
            # Update sol header with defaults from example if available
            sol_parts = []
            for name in gen.arg_names:
                if name in example:
                    sol_parts.append(f"{name}={repr(example[name])}")
                else:
                    sol_parts.append(name)
            sol_args = ", ".join(sol_parts)
            sol = f"def sol({sol_args}):"
        else:
            sol = "def sol():"

        return {
            "docstring": docstring,
            "sat": sat_code,
            "sol": sol,
            "ans_type": ans_type,
            "example": example,
        }
    except AttributeError:
        # Expected when puzzle doesn't exist in this module
        return None
    except Exception as e:
        # Only print unexpected errors
        print(f"Unexpected error extracting {puzzle_name} from {file_path.name}: {e}")
        return None


def get_available_puzzles(language="javascript"):
    """
    Get a list of available puzzle names for the specified language.

    Args:
        language (str): "javascript" or "python"

    Returns:
        list: List of puzzle names available for the language
    """
    puzzles = []

    if language == "javascript":
        # Search JS generator files
        for file_path in js_generators_dir.glob("*.js"):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
                # Find all class names
                class_matches = re.findall(
                    r"export class (\w+) extends PuzzleGenerator", content
                )
                puzzles.extend(class_matches)
            except:
                continue

    elif language == "python":
        # Search Python generator files
        for file_path in python_generators_dir.glob("*.py"):
            if file_path.name != "__init__.py":
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        content = f.read()
                    # Find all class names
                    class_matches = re.findall(
                        r"class (\w+)\(PuzzleGenerator\):", content
                    )
                    puzzles.extend(class_matches)
                except:
                    continue

    return sorted(list(set(puzzles)))  # Remove duplicates and sort


def generate_puzzle_assets(output_dir="assets"):
    """
    Generate a single JSON asset file containing all puzzle information.

    Args:
        output_dir (str): Directory to save the JSON file
    """
    os.makedirs(output_dir, exist_ok=True)

    # Load ratings
    ratings_file = project_root / "build_src" / "puzzle_ratings.json"
    ratings = {}
    if ratings_file.exists():
        with open(ratings_file, "r", encoding="utf-8") as f:
            ratings_data = json.load(f)
            for item in ratings_data:
                ratings[item["puzzle_name"]] = item["rating"]
        print(f"Loaded ratings for {len(ratings)} puzzles")
    else:
        print("Warning: puzzle_ratings.json not found, ratings will be None")

    languages = ["javascript", "python"]
    all_puzzles = {"javascript": {}, "python": {}}

    # First, collect Python ans_types
    python_ans_types = {}
    for file_path in python_generators_dir.glob("*.py"):
        if file_path.name != "__init__.py":
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
                # Find all class names
                class_matches = re.findall(r"class (\w+)\(PuzzleGenerator\):", content)
                for puzzle_name in class_matches:
                    info = extract_python_puzzle_info(file_path, puzzle_name)
                    if info and info["ans_type"]:
                        python_ans_types[puzzle_name] = info["ans_type"]
            except:
                continue

    # Type mapping from Python to JavaScript
    type_map = {
        "int": "number",
        "float": "number",
        "str": "string",
        "bool": "boolean",
        "List": "Array",
    }

    for language in languages:
        puzzles = get_available_puzzles(language)

        for puzzle_name in puzzles:
            if language == "javascript":
                # Search JS generator files
                for file_path in js_generators_dir.glob("*.js"):
                    info = extract_js_puzzle_info(file_path, puzzle_name)
                    if info:
                        # Skip puzzles with null rating
                        rating = ratings.get(puzzle_name, None)
                        if rating is None:
                            break
                        # Get ans_type from Python version
                        py_ans_type = python_ans_types.get(puzzle_name, "any")
                        ans_type = type_map.get(py_ans_type, py_ans_type)
                        all_puzzles[language][puzzle_name] = {
                            "name": puzzle_name,
                            "language": language,
                            "docstring": info["docstring"],
                            "sat": info["sat"],
                            "sol": info["sol"],
                            "ans_type": ans_type,
                            "rating": rating,
                            "example": info.get("example", {}),
                        }
                        print(f"Processed {language}/{puzzle_name}")
                        break
            elif language == "python":
                # Search Python generator files
                for file_path in python_generators_dir.glob("*.py"):
                    if file_path.name != "__init__.py":
                        info = extract_python_puzzle_info(file_path, puzzle_name)
                        if info:
                            # Skip puzzles with null rating
                            rating = ratings.get(puzzle_name, None)
                            if rating is None:
                                break
                            all_puzzles[language][puzzle_name] = {
                                "name": puzzle_name,
                                "language": language,
                                "docstring": info["docstring"],
                                "sat": info["sat"],
                                "sol": info["sol"],
                                "ans_type": info["ans_type"],
                                "rating": rating,
                                "example": info.get("example", {}),
                            }
                            break

    output_file = Path(output_dir) / "puzzles.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(all_puzzles, f, indent=2, ensure_ascii=False)

    print(f"Generated {output_file}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        puzzle_name = sys.argv[1]
        # Find and print the prompt for the puzzle
        found = False
        for file_path in js_generators_dir.glob("*.js"):
            info = extract_js_puzzle_info(file_path, puzzle_name)
            if info:
                print(f"--- JavaScript: {puzzle_name} ---")
                print("Docstring:", info["docstring"])
                print("SAT:", info["sat"])
                print("SOL:", info["sol"])
                print("Example:", info.get("example", {}))
                found = True
                break

        if not found:
            for file_path in python_generators_dir.glob("*.py"):
                if file_path.name != "__init__.py":
                    info = extract_python_puzzle_info(file_path, puzzle_name)
                    if info:
                        print(f"--- Python: {puzzle_name} ---")
                        print("Docstring:", info["docstring"])
                        print("SAT:", info["sat"])
                        print("SOL:", info["sol"])
                        print("Example:", info.get("example", {}))
                        found = True
                        break
    else:
        # Generate puzzle assets
        generate_puzzle_assets()
